.PHONY: clean All

All:
	@echo "----------Building project:[ HW1 - Debug ]----------"
	@$(MAKE) -f  "HW1.mk"
clean:
	@echo "----------Cleaning project:[ HW1 - Debug ]----------"
	@$(MAKE) -f  "HW1.mk" clean
